remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: nsquared agents
description: Downloads and guides for the nsquared agents desktop characters.
